image: mhndev/docker-lua

DUConfigs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt install git
    - git config --global http.sslVerify false
    - git submodule update --recursive --remote
  script:
    - lua $CI_PROJECT_DIR/dependencies/dubuild/compiler.lua ./config/Compiler_Config.json -f "STEC.json" ./dependencies/dubuild/template.json ./output
    - lua $CI_PROJECT_DIR/dependencies/dubuild/compiler.lua ./config/Compiler_Config.min.json -f "STEC.min.json" ./dependencies/dubuild/template.json ./output
    - lua $CI_PROJECT_DIR/dependencies/dubuild/compiler.lua ./config/Compiler_Config.crypt.json -f "%s.STEC.crypt.json" ./dependencies/dubuild/template.json ./output
  artifacts:
    paths:
    - ./output/*.json