image: mhndev/docker-lua

DUConfigs:
  script:
    - lua $CI_PROJECT_DIR/dubuild/compiler.lua Compiler_Config.json ./dubuild/template.json STEC.json
    - lua $CI_PROJECT_DIR/dubuild/compiler.lua Compiler_Config.min.json ./dubuild/template.json STEC.min.json
  artifacts:
    paths:
    - STEC.json
    - STEC.min.json

Encrypted_CID1:
  script:
    - lua $CI_PROJECT_DIR/dubuild/compiler.lua Compiler_Config.crypt.json ./dubuild/template.json STEC.crypt.json
  artifacts:
    paths:
    - STEC.crypt.json